# Generated by Django 3.1.5 on 2021-01-04 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0005_sharednews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharednews',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='sharednews',
            name='user',
            field=models.ManyToManyField(related_name='shared_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
