# Generated by Django 3.1.4 on 2021-01-04 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_auto_20210104_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednews',
            name='datetime_shared',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
