# Generated by Django 3.1.4 on 2021-01-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_auto_20210104_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednews',
            name='datetime_shared',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sharednews',
            name='image',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='sharednews',
            name='url',
            field=models.TextField(max_length=2048),
        ),
    ]
