# Generated by Django 3.1.4 on 2021-01-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_auto_20210104_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednews',
            name='caption',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='sharednews',
            name='description',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='sharednews',
            name='title',
            field=models.TextField(max_length=512),
        ),
    ]
