# Generated by Django 3.1.4 on 2021-01-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_auto_20210104_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednews',
            name='image',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='sharednews',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
