# Generated by Django 3.1.4 on 2021-01-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_auto_20210104_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednews',
            name='full_name',
            field=models.CharField(default='Default', max_length=64),
            preserve_default=False,
        ),
    ]
